import assert from 'node:assert/strict';
import {readdir,readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {Miniflare}=createRequire(require.resolve('wrangler'))('miniflare');
const root=path.resolve('dist/server');
const names=(await readdir(root,{recursive:true})).filter(x=>x.endsWith('.js')).sort((a,b)=>(a==='index.js'?-1:b==='index.js'?1:0));
const mf=new Miniflare({modules:names.map(name=>({type:'ESModule',path:path.join(root,name)})),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],assets:{directory:path.resolve('dist/client'),routerConfig:{has_user_worker:true}}});
let checks=0;
function check(value,msg){assert.ok(value,msg);checks++;console.log('PASS',msg)}
async function call(user,path,method='GET',input,expected=200,origin='https://orbit.test'){const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.com'};if(!user){delete headers['oai-authenticated-user-id'];delete headers['oai-authenticated-user-email']}if(method!=='GET'){headers['Content-Type']='application/json';headers.Origin=origin}const r=await mf.dispatchFetch('https://orbit.test/api/'+path,{method,headers,body:input===undefined?undefined:JSON.stringify(input)});const raw=await r.text();assert.equal(r.status,expected,`${method} ${path} expected ${expected}, got ${r.status}: ${raw.slice(0,800)}`);return JSON.parse(raw)}
try{const d=await mf.getD1Database('DB');for(const file of(await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort()){for(const sql of(await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').filter(x=>x.trim()))await d.prepare(sql).run()}
await call('','workspace','GET',undefined,401);check(true,'Anonymous API access is denied');
let a=await call('test-owner-a','workspace');check(!a.clients.length&&!a.entries.length,'New account has no sample or other client data');
a=await call('test-owner-a','clients','POST',{name:'Alpha',website:'https://example.com',goals:'Grow relevant demand'});const alpha=a.clientId;
a=await call('test-owner-a','entries','POST',{clientId:alpha,kind:'keyword',title:'industrial cooling',data:{position:8,previous:12,url:'https://example.com/products'}});const keyword=a.entries.find(x=>x.kind==='keyword');check(keyword.data.position===8,'Validated keyword persists');
a=await call('test-owner-a','entries','POST',{clientId:alpha,kind:'task',title:'Improve product page',relatedId:keyword.id,data:{channel:'SEO'}});const task=a.entries.find(x=>x.kind==='task');check(task.relatedId===keyword.id,'Task links to its supporting keyword');
a=await call('test-owner-a','entries','PATCH',{...task,status:'Done'});check(a.entries.find(x=>x.id===task.id).status==='Done','Task status updates persist');
const beta=(await call('test-owner-a','clients','POST',{name:'Beta'})).clientId;
await call('test-owner-a','entries','POST',{clientId:beta,kind:'task',title:'Cross client reference',relatedId:keyword.id},400);check(true,'Cross-client record links are rejected');
const betaData=await call('test-owner-a','workspace?client='+beta);check(betaData.entries.length===0&&betaData.metrics.length===0,'Switching clients returns only the selected client records');
const b=await call('test-owner-b','workspace');check(!b.clients.length,'Second user gets an isolated organization');
await call('test-owner-b','workspace?client='+alpha,'GET',undefined,404);await call('test-owner-b','entries','PATCH',{...task,title:'Unauthorized'},404);await call('test-owner-b','entries','DELETE',{id:keyword.id},404);check(true,'Tenant boundaries reject reads, edits, and deletion');
await call('test-owner-a','entries','POST',{clientId:alpha,kind:'keyword',title:'Unsafe URL',data:{url:'javascript:alert(1)'}},400);await call('test-owner-a','entries','POST',{clientId:alpha,kind:'keyword',title:'Invalid metric',data:{volume:-1}},400);check(true,'Unsafe URLs and negative metrics are rejected');
await call('test-owner-a','clients','POST',{name:'CSRF'},403,'https://untrusted.example');check(true,'Cross-origin mutation is denied');
await call('test-owner-a','entries','POST',{clientId:alpha,kind:'automation',title:'Qualified follow-up',status:'Active',data:{trigger:'Lead created',condition:'Value above threshold',threshold:100,action:'Create follow-up task',taskTitle:'Call new lead',days:2}});
a=await call('test-owner-a','entries','POST',{clientId:alpha,kind:'lead',title:'Test contact',data:{value:500,email:'contact@example.com',source:'Referral'}});const lead=a.entries.find(x=>x.kind==='lead');check(a.entries.some(x=>x.kind==='task'&&x.relatedId===lead.id&&x.title.includes('Call new lead')),'Active automation creates a linked follow-up task atomically');
const beforeTasks=a.entries.filter(x=>x.kind==='task').length;a=await call('test-owner-a','entries','POST',{clientId:alpha,kind:'lead',title:'Below threshold',data:{value:50}});check(a.entries.filter(x=>x.kind==='task').length===beforeTasks,'Automation condition excludes below-threshold leads');
a=await call('test-owner-a','import','POST',{clientId:alpha,kind:'analytics',rows:[{date:'2026-09-01',sessions:1000,organic:400,leads:20,conversions:10,spend:100,revenue:300}]});check(a.metrics[0].sessions===1000,'Analytics import persists with selected client');
a=await call('test-owner-a','import','POST',{clientId:alpha,kind:'analytics',rows:[{date:'2026-09-01',sessions:1500,leads:30}]});check(a.metrics.length===1&&a.metrics[0].sessions===1500,'Reimport updates the matching date without duplication');
await call('test-owner-a','import','POST',{clientId:alpha,kind:'keyword',rows:[{title:'Valid first row'},{title:'Invalid next row',position:-1}]},400);a=await call('test-owner-a','workspace?client='+alpha);check(!a.entries.some(x=>x.title==='Valid first row'),'Invalid import is rejected without partial writes');
a=await call('test-owner-a','audit','POST',{clientId:alpha,url:'https://example.com',html:'<!doctype html><html lang="en"><head><title>Demo</title><meta name="description" content="Details"><meta name="viewport" content="width=device-width"><link rel="canonical" href="https://example.com"></head><body><h1>Example</h1><img src="/a.png" alt="A useful description"></body></html>'});check(a.entries.find(x=>x.kind==='audit').data.score===100,'HTML source audit inspects and saves actual markup checks');
a=await call('test-owner-a','reports','POST',{clientId:alpha,title:'September report',days:30});const report=a.entries.find(x=>x.kind==='report');check(report.data.metrics.sessions===1500&&report.data.client.id===alpha,'Report snapshots the current client metrics');
check(report.data.start==='2026-08-03'&&report.data.end==='2026-09-01','Report labels include exactly the selected 30 calendar days');
const reportResponse=await mf.dispatchFetch('https://orbit.test/reports/'+report.id,{headers:{'oai-authenticated-user-id':'test-owner-a','oai-authenticated-user-email':'test-owner-a@example.com'}});check(reportResponse.status===200&&(await reportResponse.text()).includes('September report'),'Authenticated printable report route renders');
await call('test-owner-a','members','POST',{clientId:alpha,email:'test-analyst@example.com',role:'Analyst'});const analyst=await call('test-analyst','workspace?client='+alpha);check(analyst.role==='Analyst','Invited role is claimed by the matching authenticated email');await call('test-analyst','entries','PATCH',{...task,status:'To do'},403);await call('test-analyst','members','POST',{email:'someone@example.com',role:'Admin'},403);check(true,'Read-only role cannot edit records or grant access');
await call('test-owner-a','members','POST',{clientId:alpha,email:'test-client@example.com',role:'Client',assignedClient:alpha});const client=await call('test-client','workspace');check(client.clients.length===1&&client.clientId===alpha,'Client role is limited to assigned client');await call('test-client','workspace?client='+beta,'GET',undefined,404);
a=await call('test-owner-a','entries','DELETE',{id:keyword.id});check(!a.entries.some(x=>x.id===keyword.id)&&a.entries.find(x=>x.id===task.id).relatedId==='','Delete clears dependent references and keeps tasks');
const reloaded=await call('test-owner-a','workspace?client='+alpha);check(reloaded.entries.some(x=>x.id===report.id),'Records survive subsequent independent requests');
await call('test-owner-a','assistant','POST',{clientId:alpha,question:'What next?'},503);check(true,'Unconfigured AI returns a clear unavailable state');
console.log(`\n${checks} integration checks passed.`)}finally{await mf.dispose()}
