'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Choice} from './record-list';
import {parseCsv} from '@/lib/import-csv';
import {Download,Upload} from 'lucide-react';
export const templates:Record<string,string>={analytics:'date,sessions,organic,paid,social,referral,direct,leads,conversions,spend,revenue,impressions,clicks\n2026-09-01,1000,400,250,100,100,150,24,15,500,1500,8000,320',keyword:'title,status,position,previous,volume,difficulty,cpc,intent,cluster,country,device,source,url\nexample keyword,Tracking,12,16,300,40,2,Commercial,Products,United States,Desktop,Your source,https://example.com',campaign:'title,status,platform,spend,impressions,clicks,conversions,revenue,url,notes\nSeptember search,Active,Google Ads,500,12000,600,25,1800,https://example.com,Manual export',lead:'title,status,email,company,source,value,notes\nSample contact,New,person@example.com,Example company,Referral,1000,Example only',product:'title,status,sku,category,url,views,orders,revenue,abandoned\nSample product,Active,SKU-001,Products,https://example.com,500,12,2400,3'};
export function downloadText(text:string,name:string,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export function ImportDialog({initialKind,onClose,onImport}:{initialKind:string;onClose:()=>void;onImport:(kind:string,rows:any[])=>Promise<void>}){const[kind,setKind]=useState(initialKind in templates?initialKind:'analytics'),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any[]|null>(null);const labels:Record<string,string>={analytics:'Daily analytics',keyword:'Keywords',campaign:'Campaigns',lead:'Leads',product:'Products'};return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>Bring your data into Orbit</DialogTitle><DialogDescription>Import a CSV from your existing tools. Review the rows before saving.</DialogDescription></DialogHeader><div className="toolbar"><Choice label="Data type" value={labels[kind]} options={Object.values(labels)} onChange={v=>{setKind(Object.keys(labels).find(k=>labels[k]===v)!);setPreview(null)}}/><button className="button" onClick={()=>downloadText(templates[kind],'orbit-'+kind+'-template.csv')}><Download size={14}/>Template</button></div><label className="field">CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>1000000){setError('Choose a CSV smaller than 1 MB.');return}setText(await f.text());setPreview(null);setError('')}}/></label><label className="field" style={{marginTop:16}}>Or paste your CSV<Textarea rows={7} value={text} onChange={e=>{setText(e.target.value);setPreview(null)}} placeholder={templates[kind].split('\n')[0]} style={{fontFamily:'monospace',fontSize:12}}/></label><p className="muted small">Up to 500 rows. Analytics replaces matching dates. Other record types append rows. All money values are USD.</p>{preview&&<div className="alert-inline" style={{marginTop:16}}><strong>{preview.length} rows ready.</strong><p>Columns: {Object.keys(preview[0]||{}).join(', ')}</p></div>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="button" onClick={onClose}>Cancel</button>{!preview?<button className="button primary" onClick={()=>{try{const rows=parseCsv(text);if(!rows.length)throw Error('Add at least one data row.');setPreview(rows);setError('')}catch(e){setError((e as Error).message)}}}>Review import</button>:<button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{await onImport(kind,preview);onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Importing…':'Import '+preview.length+' rows'}</button>}</div></DialogContent></Dialog>}
