'use client';
import {useState} from 'react';
import {Search,ArrowUpRight,ArrowDownRight,MoreHorizontal,Trash2,Layers,Check,ArrowRight} from 'lucide-react';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import type {Entry,ModuleDef} from '@/lib/types';
import {number,currency,ratio} from '@/lib/insights';
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger className="compact-select" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
export function Status({value}:{value:string}){const green=['Done','Published','Customer','Healthy','Active','Approved','Mentioned','Cited','Validated','Complete'];const blue=['In progress','Tracking','Improving','Qualified','Live','Conversation'];return <span className={'pill '+(green.includes(value)?'':blue.includes(value)?'blue':['High','Needs attention','Review','In review','Not present'].includes(value)?'orange':'gray')}>{value}</span>}
export function RecordTable({items,def,edit,remove,update,editable}:{items:Entry[];def:ModuleDef;edit:(e:Entry)=>void;remove:(e:Entry)=>void;update:(e:Entry)=>void;editable:boolean}){const kind=def.kind;const columns=kind==='keyword'?['Keyword','Position','Change','Volume','Intent','Status']:kind==='campaign'?['Campaign','Platform','Spend','Conversions','CPA','ROAS','Status']:kind==='lead'?['Contact','Company','Source','Value','Stage']:kind==='competitor'?['Competitor','Website','Est. traffic','Source']:kind==='visibility'?['Observation','Platform','Query','Checked','Status']:kind==='product'?['Product','Views','Orders','Revenue','Conversion']:kind==='landing'?['Landing page','Sessions','Conversions','Rate','Status']:['task','content','social','email','pr','page','persona','project','automation'].includes(kind||'')?['Name',kind==='task'?'Workstream':kind==='content'?'Format':kind==='social'?'Channel':kind==='pr'?'Publication':kind==='persona'?'Job title':'Details','Owner','Due date','Status']:['Name','Status','Updated'];function cells(e:Entry){const d=e.data;const title=<><button className="row-title" onClick={()=>edit(e)}>{e.title}</button>{kind==='keyword'&&<p className="cell-sub">{String(d.url||'').replace(/^https?:\/\//,'').slice(0,45)}</p>}</>;if(kind==='keyword'){const move=Number(d.previous)-Number(d.position);return [title,d.position?'#'+d.position:'—',move?<span className={move>0?'positive':'negative'} style={{display:'inline-flex',alignItems:'center',gap:3}}>{move>0?<ArrowUpRight size={12}/>:<ArrowDownRight size={12}/>} {Math.abs(move)}</span>:'—',number(Number(d.volume)),d.intent||'—',<Status value={e.status}/>]}if(kind==='campaign')return [title,d.platform||'—',currency(Number(d.spend)),number(Number(d.conversions)),Number(d.conversions)?currency(Number(d.spend)/Number(d.conversions)):'—',Number(d.spend)?(Number(d.revenue)/Number(d.spend)).toFixed(2)+'×':'—',<Status value={e.status}/>];if(kind==='lead')return [<>{title}<p className="cell-sub">{d.email}</p></>,d.company||'—',d.source||'—',currency(Number(d.value)),<Status value={e.status}/>];if(kind==='competitor')return [title,String(d.website||'').replace(/^https?:\/\//,'').replace(/\/$/,''),number(Number(d.traffic)),d.source||'Not provided'];if(kind==='visibility')return [title,d.platform,d.query,d.checkedAt||'—',<Status value={e.status}/>];if(kind==='product')return [title,number(Number(d.views)),number(Number(d.orders)),currency(Number(d.revenue)),ratio(Number(d.orders),Number(d.views))+'%'];if(kind==='landing')return [title,number(Number(d.sessions)),number(Number(d.conversions)),ratio(Number(d.conversions),Number(d.sessions))+'%',<Status value={e.status}/>];return [title,d.channel||d.format||d.platform||d.publication||d.jobTitle||d.subject||d.url||d.trigger||'—',e.owner||'Unassigned',e.dueDate?new Date(e.dueDate+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—',<Status value={e.status}/>]}
return <div className="panel"><Table className="work-table"><TableHeader><TableRow>{columns.map(c=><TableHead key={c}>{c}</TableHead>)}<TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{items.map(e=><TableRow key={e.id}>{cells(e).map((v,i)=><TableCell key={i}>{v}</TableCell>)}<TableCell><DropdownMenu><DropdownMenuTrigger asChild><button className="small-link" aria-label={'Actions for '+e.title}><MoreHorizontal size={18}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>edit(e)}>Open details</DropdownMenuItem>{editable&&def.statuses?.map(s=><DropdownMenuItem key={s} onClick={()=>update({...e,status:s})}>Move to {s}</DropdownMenuItem>)}{editable&&<DropdownMenuItem className="text-destructive" onClick={()=>remove(e)}>Delete</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>}
export function Kanban({items,def,edit}:{items:Entry[];def:ModuleDef;edit:(e:Entry)=>void}){return <div className="kanban">{(def.statuses||[]).map(status=><div className="kanban-column" key={status}><div className="kanban-heading"><span>{status}</span><span>{items.filter(x=>x.status===status).length}</span></div>{items.filter(x=>x.status===status).map(x=><button className="kanban-card" style={{width:'100%',textAlign:'left'}} key={x.id} onClick={()=>edit(x)}><span className="pill gray">{x.data.channel||x.data.format||x.data.platform||def.singular}</span><h3 style={{marginTop:10}}>{x.title}</h3>{x.kind==='lead'&&<p>{x.data.company} · {currency(Number(x.data.value))}</p>}<div className="kanban-card-foot"><span>{x.dueDate||'No due date'}</span><span>{x.priority}</span></div></button>)}</div>)}</div>}
export function CalendarView({items,edit}:{items:Entry[];edit:(e:Entry)=>void}){const[date,setDate]=useState(new Date());const start=new Date(date.getFullYear(),date.getMonth(),1);const offset=(start.getDay()+6)%7;const days=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();return <><div className="toolbar"><h2>{date.toLocaleDateString('en-US',{month:'long',year:'numeric'})}</h2><div className="toolbar-left"><button className="button" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()-1,1))}>Previous</button><button className="button" onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()+1,1))}>Next</button></div></div><div className="calendar-wrap"><div className="calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><div className="calendar-cell calendar-day" key={d}>{d}</div>)}{Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>{const d=i-offset+1;const key=new Date(Date.UTC(date.getFullYear(),date.getMonth(),d)).toISOString().slice(0,10);return <div className="calendar-cell" key={i}>{d>0&&d<=days&&<><span>{d}</span>{items.filter(x=>x.dueDate===key).map(x=><button className="calendar-event" key={x.id} onClick={()=>edit(x)}>{x.title}</button>)}</>}</div>})}</div></div></>}
