import type {Client,Entry,DailyMetric,Workspace} from './types';
const now=new Date();const day=(delta:number)=>new Date(now.getTime()+delta*86400000).toISOString().slice(0,10);
export const demoClients:Client[]=[{id:'demo-uhe',orgId:'demo',name:'United Heat Exchangers',website:'https://example.com',industry:'Industrial manufacturing',location:'Chennai, India',market:'B2B buyers across India',goals:'Increase qualified enquiries and grow non-branded organic visibility.',audience:'Plant managers, procurement leads, and process engineers.',guidelines:'Precise, technically credible, approachable. Avoid unsupported performance claims.',logo:'',color:'#4169e1',demo:true,createdAt:now.toISOString()},{id:'demo-fern',orgId:'demo',name:'Fern & Form',website:'https://example.org',industry:'Home & living',location:'London, UK',market:'UK homeowners',goals:'Grow product discovery and repeat purchases.',audience:'Design-conscious homeowners.',guidelines:'Warm, clear, material-led.',logo:'',color:'#bb7c40',demo:true,createdAt:now.toISOString()}];
function e(kind:string,id:string,title:string,status:string,data:Record<string,any>,extra:Partial<Entry>={}):Entry{return {id,clientId:'demo-uhe',kind,title,status,priority:'Medium',owner:'Unassigned',dueDate:'',projectId:'',relatedId:'',data,createdAt:now.toISOString(),updatedAt:now.toISOString(),...extra}}
export const demoEntries:Entry[]=[
e('project','proj-q4','Q4 organic growth','In progress',{description:'Build qualified organic demand across key product categories.'}),
e('task','task-1','Refresh the plate heat exchanger guide','In progress',{channel:'SEO',description:'Review search intent, refresh technical details and improve internal links.'},{priority:'High',dueDate:day(2),projectId:'proj-q4',relatedId:'content-1'}),
e('task','task-2','Review the September search campaign','To do',{channel:'Advertising',description:'Compare cost per qualified enquiry before proposing budget changes.'},{priority:'High',dueDate:day(1),relatedId:'campaign-1'}),
e('task','task-3','Publish the maintenance checklist','In review',{channel:'Content',description:'Complete the technical review and final metadata.'},{dueDate:day(4),projectId:'proj-q4'}),
e('task','task-4','Add missing image descriptions','To do',{channel:'Website',description:'Review the images on service pages for meaningful alternative text.'},{dueDate:day(6),priority:'Low'}),
e('task','task-5','Map product keywords to landing pages','Done',{channel:'SEO'},{dueDate:day(-2),projectId:'proj-q4'}),
e('keyword','kw-1','plate heat exchanger','Improving',{position:8,previous:11,volume:4400,difficulty:42,cpc:2.3,intent:'Commercial',cluster:'Heat exchangers',country:'India',device:'Desktop',url:'https://example.com/plate-heat-exchangers',source:'Demo dataset'}),
e('keyword','kw-2','heat exchanger manufacturer','Tracking',{position:5,previous:6,volume:2900,difficulty:38,cpc:3.1,intent:'Transactional',cluster:'Manufacturers',country:'India',device:'Desktop',url:'https://example.com',source:'Demo dataset'}),
e('keyword','kw-3','shell and tube heat exchanger','Needs attention',{position:14,previous:10,volume:3600,difficulty:46,cpc:2.8,intent:'Commercial',cluster:'Heat exchangers',country:'India',device:'Mobile',url:'https://example.com/shell-and-tube',source:'Demo dataset'}),
e('keyword','kw-4','heat exchanger maintenance','Opportunity',{position:12,previous:18,volume:1300,difficulty:28,cpc:1.4,intent:'Informational',cluster:'Maintenance',country:'India',device:'Desktop',url:'https://example.com/maintenance',source:'Demo dataset'}),
e('keyword','kw-5','industrial cooling solutions','Tracking',{position:7,previous:7,volume:880,difficulty:34,cpc:2.1,intent:'Commercial',cluster:'Cooling',country:'India',device:'Desktop',url:'https://example.com/cooling',source:'Demo dataset'}),
e('content','content-1','Plate heat exchangers: the complete buying guide','Updating',{format:'Guide',keyword:'plate heat exchanger',url:'https://example.com/plate-heat-exchangers',body:'Audience: procurement managers comparing industrial heat exchangers.\n\nCover selection criteria, materials, maintenance, and the questions to ask a supplier.\n\nNext: validate all technical claims with a subject-matter reviewer.',metaTitle:'Plate Heat Exchangers: Buying Guide',metaDescription:'Understand selection criteria, materials and maintenance considerations for industrial plate heat exchangers.'},{dueDate:day(5),projectId:'proj-q4',relatedId:'kw-1'}),
e('content','content-2','A practical heat exchanger maintenance checklist','Review',{format:'Article',keyword:'heat exchanger maintenance',body:'Draft outline: inspection schedule, fouling signs, cleaning options, documentation. Technical review is required before publication.'},{dueDate:day(4),relatedId:'kw-4'}),
e('content','content-3','How to choose a cooling solution for your plant','Idea',{format:'Article',keyword:'industrial cooling solutions'},{dueDate:day(10)}),
e('campaign','campaign-1','Industrial heat exchangers | Search','Active',{platform:'Google Ads',spend:3240,impressions:68500,clicks:2160,conversions:36,revenue:12600,url:'https://example.com/heat-exchangers',notes:'Demonstration campaign. No advertising account is connected.'}),
e('campaign','campaign-2','Procurement decision-makers | Retargeting','Active',{platform:'Meta Ads',spend:1480,impressions:92800,clicks:1420,conversions:22,revenue:8100,url:'https://example.com/consultation'}),
e('campaign','campaign-3','Maintenance guide | Search','Paused',{platform:'Microsoft Ads',spend:640,impressions:18400,clicks:420,conversions:3,revenue:750,url:'https://example.com/maintenance'}),
e('lead','lead-1','Alex Morgan','Qualified',{company:'Example Manufacturing',email:'alex@example.com',source:'Organic search',value:12500,notes:'Interested in a capacity assessment.'},{dueDate:day(2)}),
e('lead','lead-2','Jordan Lee','New',{company:'Sample Process Systems',email:'jordan@example.com',source:'Paid search',value:8000}),
e('lead','lead-3','Taylor Kim','Opportunity',{company:'Demonstration Foods',email:'taylor@example.com',source:'Referral',value:24000}),
e('lead','lead-4','Sam Patel','Conversation',{company:'Example Engineering',email:'sam@example.com',source:'Social',value:6500}),
e('lead','lead-5','Chris Williams','Customer',{company:'Sample Industries',email:'chris@example.com',source:'Organic search',value:18000}),
e('strategy','strat-1','Strengthen product search visibility','In progress',{objective:'Increase qualified organic enquiries',horizon:'Days 1–30',kpi:'Top 10 product keywords',target:'8',budget:2500,notes:'Prioritize product pages with established demand and near-page-one rankings.'}),
e('strategy','strat-2','Build a useful technical content library','Planned',{objective:'Help buyers make a confident decision',horizon:'Days 31–60',kpi:'Reviewed guides published',target:'4',budget:1800}),
e('strategy','strat-3','Improve enquiry quality','Planned',{objective:'Increase qualified lead rate',horizon:'Days 61–90',kpi:'Qualified enquiries / all enquiries',target:'35%',budget:1200}),
e('competitor','comp-1','Apex Thermal (example)','Tracking',{website:'https://example.net',keywords:'plate heat exchanger, heat exchanger maintenance, thermal efficiency, cooling system design',traffic:18400,authority:44,source:'Illustrative competitor dataset',notes:'Reference competitor used only in the demo.'}),
e('competitor','comp-2','Flow Systems (example)','Tracking',{website:'https://example.org',keywords:'industrial cooling solutions, process cooling, heat exchanger manufacturer',traffic:14200,authority:38,source:'Illustrative competitor dataset'}),
e('social','social-1','What a well-maintained heat exchanger looks like','Planned',{platform:'LinkedIn',body:'Small maintenance decisions can have an outsized operational impact. Here are the inspection habits to discuss with your engineering team.',hashtags:'#ProcessEngineering #Maintenance',impressions:0,engagements:0},{dueDate:day(3)}),
e('social','social-2','Inside the workshop: quality checks','Draft',{platform:'Instagram',body:'A closer look at the checks behind every component.',impressions:0,engagements:0},{dueDate:day(5)}),
e('email','email-1','The monthly engineering brief','Draft',{subject:'A clearer view of heat exchanger maintenance',preheader:'A practical checklist for your next inspection.',segment:'Engineering leads',body:'Hello,\n\nThis month, we’re focusing on the small maintenance steps that help teams plan ahead.\n\nExplore our checklist and share it with your team.',cta:'Read the checklist',url:'https://example.com/maintenance',recipients:0,opens:0,clicks:0}),
e('page','page-1','Product overview','Needs attention',{url:'https://example.com/plate-heat-exchangers',purpose:'Product discovery',technology:'WordPress',notes:'Review alternative text and internal links.'}),
e('landing','landing-1','Talk to a thermal specialist','Live',{url:'https://example.com/consultation',headline:'Find the right fit for your process.',cta:'Discuss your requirements',sessions:840,conversions:22,notes:'Test a shorter form and clearer expectations about the consultation.'}),
e('persona','persona-1','The plant operations manager','Research',{jobTitle:'Plant Operations Manager',industry:'Manufacturing · 100–500 employees',goals:'Reliable processes, predictable maintenance, better equipment decisions.',challenges:'Downtime risk, complex specifications, pressure to justify expenditure.',triggers:'Planned upgrades, recurring maintenance issues, capacity expansion.',channels:'Google, technical guides, LinkedIn, supplier recommendations.',decision:'Engineering review followed by procurement approval.'}),
e('pr','pr-1','Maintenance insight for an industry newsletter','Research',{publication:'Example Engineering Review',contact:'Editorial desk',email:'editor@example.com',url:'https://example.net',notes:'Develop a practical contribution. No outreach has been sent.'}),
e('visibility','vis-1','Industrial supplier visibility check','Mentioned',{platform:'Google Search',query:'heat exchanger manufacturer India',url:'https://example.com',checkedAt:day(-2),notes:'Demonstration observation; not a live search result.'}),
e('visibility','vis-2','Answer engine citation review','Not present',{platform:'Perplexity',query:'how to choose a plate heat exchanger',checkedAt:day(-2),notes:'Demonstration observation.'}),
e('automation','auto-1','New lead → follow-up task','Draft',{trigger:'Lead created',condition:'Every lead',threshold:0,action:'Create follow-up task',taskTitle:'Follow up with the new enquiry',days:2}),
e('audit','audit-demo','Illustrative website review','Complete',{url:'https://example.com',score:84,source:'Demo assessment',checks:[{name:'Title and description',status:'pass',detail:'Present in the demonstration dataset.'},{name:'Image alternative text',status:'warning',detail:'3 illustrative images need descriptions.'},{name:'Heading hierarchy',status:'pass',detail:'One H1 in the demonstration page.'},{name:'Keyboard navigation',status:'manual',detail:'Requires a human review.'}],checkedAt:day(-3)}),
e('notification','notice-1','A product keyword entered the top 10','Unread',{module:'seo',detail:'plate heat exchanger moved from position 11 to 8 in the sample data.'}),
e('notification','notice-2','Your guide is ready for review','Unread',{module:'content',detail:'Review the maintenance checklist before it moves to approval.'})
];
export function demoMetrics(scale=1):DailyMetric[]{return Array.from({length:180},(_,i)=>{const trend=.7+i*.0025;const wave=Math.sin(i*1.3)*90+Math.cos(i*.4)*55;const sessions=Math.round((590*trend+wave)*scale);const organic=Math.round(sessions*.51),paid=Math.round(sessions*.24),social=Math.round(sessions*.11),referral=Math.round(sessions*.07);return {date:day(i-179),sessions,organic,paid,social,referral,direct:sessions-organic-paid-social-referral,leads:Math.max(1,Math.round((4+Math.sin(i*.7)*2+i*.013)*scale)),conversions:Math.max(1,Math.round((3+Math.sin(i*.6)+i*.01)*scale)),spend:Math.round((125+Math.sin(i)*28)*scale),revenue:Math.round((750+Math.sin(i*.8)*280+i*2)*scale),impressions:Math.round(sessions*5.4),clicks:Math.round(sessions*.3)}})}
export function previewWorkspace():Workspace{return {user:{id:'demo',name:'Your workspace',email:''},organization:{id:'demo',name:'Orbit workspace'},role:'Owner',clients:demoClients,entries:demoEntries,metrics:demoMetrics(),clientId:'demo-uhe',members:[],aiEnabled:false,demoMode:true}}
