import type {ModuleDef} from './types';
const status=['Planned','In progress','In review','Done'];
export const modules:ModuleDef[]=[
{id:'dashboard',label:'Dashboard',group:'Workspace',description:'The whole picture. A clear next step.'},
{id:'clients',label:'Clients',group:'Workspace',description:'A dedicated workspace for every business.'},
{id:'strategy',label:'Strategy',group:'Intelligence',kind:'strategy',singular:'initiative',description:'Connect the business goals to the work that gets you there.',statuses:status,fields:[{key:'objective',label:'Business objective',required:true},{key:'horizon',label:'Planning horizon',type:'select',options:['Days 1–30','Days 31–60','Days 61–90','Annual']},{key:'kpi',label:'Success metric'},{key:'target',label:'Target'},{key:'budget',label:'Budget (USD)',type:'number'},{key:'notes',label:'Positioning, approach and risks',type:'textarea'}]},
{id:'seo',label:'SEO',group:'Intelligence',kind:'keyword',singular:'keyword',description:'Find the search opportunities and turn them into progress.',statuses:['Tracking','Opportunity','Improving','Needs attention'],fields:[{key:'url',label:'Ranking URL',type:'url'},{key:'position',label:'Current position',type:'number'},{key:'previous',label:'Previous position',type:'number'},{key:'volume',label:'Monthly search volume',type:'number'},{key:'difficulty',label:'Difficulty (0–100)',type:'number'},{key:'cpc',label:'CPC (USD)',type:'number'},{key:'intent',label:'Search intent',type:'select',options:['Informational','Commercial','Transactional','Navigational']},{key:'cluster',label:'Keyword cluster'},{key:'country',label:'Country'},{key:'device',label:'Device',type:'select',options:['Desktop','Mobile']},{key:'source',label:'Data source'}]},
{id:'search-everywhere',label:'Search Everywhere',group:'Intelligence',kind:'visibility',singular:'observation',description:'A shared view of your brand across search and answer engines.',statuses:['Mentioned','Cited','Not present','Not checked'],fields:[{key:'platform',label:'Platform',type:'select',options:['Google Search','ChatGPT','Perplexity','Gemini','Bing','YouTube','Featured snippet','Knowledge panel']},{key:'query',label:'Query checked',required:true},{key:'url',label:'Evidence URL',type:'url'},{key:'checkedAt',label:'Checked date',type:'date'},{key:'notes',label:'Evidence and opportunity',type:'textarea'}]},
{id:'ai-consultant',label:'AI Consultant',group:'Intelligence',description:'Ask better questions of the data you already have.'},
{id:'analytics',label:'Analytics',group:'Intelligence',description:'Follow traffic, conversions and revenue in one place.'},
{id:'competitors',label:'Competitors',group:'Intelligence',kind:'competitor',singular:'competitor',description:'Understand the gaps. Find your next opening.',statuses:['Tracking','Review needed'],fields:[{key:'website',label:'Website',type:'url',required:true},{key:'keywords',label:'Ranking keywords (comma separated)',type:'textarea'},{key:'traffic',label:'Estimated monthly traffic',type:'number'},{key:'authority',label:'Authority indicator',type:'number'},{key:'source',label:'Source and date'},{key:'notes',label:'Positioning and observations',type:'textarea'}]},
{id:'content',label:'Content',group:'Marketing',kind:'content',singular:'content item',description:'From a promising idea to a piece worth publishing.',statuses:['Idea','Research','Brief','Draft','Review','Approved','Published','Updating'],fields:[{key:'format',label:'Format',type:'select',options:['Article','Landing page','Video','Case study','Guide','FAQ']},{key:'keyword',label:'Target keyword'},{key:'url',label:'Published URL',type:'url'},{key:'body',label:'Brief / article',type:'textarea'},{key:'metaTitle',label:'Meta title'},{key:'metaDescription',label:'Meta description',type:'textarea'}]},
{id:'advertising',label:'Advertising',group:'Marketing',kind:'campaign',singular:'campaign',description:'Track performance and plan budgets with a clear view of return.',statuses:['Draft','Active','Paused','Completed'],fields:[{key:'platform',label:'Platform',type:'select',options:['Google Ads','Microsoft Ads','Meta Ads']},{key:'spend',label:'Spend (USD)',type:'number'},{key:'impressions',label:'Impressions',type:'number'},{key:'clicks',label:'Clicks',type:'number'},{key:'conversions',label:'Conversions',type:'number'},{key:'revenue',label:'Revenue (USD)',type:'number'},{key:'url',label:'Landing page',type:'url'},{key:'notes',label:'Campaign objective and notes',type:'textarea'}]},
{id:'social',label:'Social Media',group:'Marketing',kind:'social',singular:'post',description:'Plan the conversation across your social channels.',statuses:['Idea','Draft','Review','Approved','Planned','Published'],fields:[{key:'platform',label:'Channel',type:'select',options:['LinkedIn','Instagram','Facebook','X','YouTube','TikTok']},{key:'body',label:'Post copy',type:'textarea',required:true},{key:'hashtags',label:'Hashtags'},{key:'url',label:'Published post URL',type:'url'},{key:'impressions',label:'Impressions',type:'number'},{key:'engagements',label:'Engagements',type:'number'}]},
{id:'email',label:'Email',group:'Marketing',kind:'email',singular:'email campaign',description:'Build thoughtful emails for the right audience.',statuses:['Draft','Review','Ready','Sent'],fields:[{key:'subject',label:'Subject line',required:true},{key:'preheader',label:'Preview text'},{key:'segment',label:'Audience segment'},{key:'body',label:'Email body',type:'textarea'},{key:'cta',label:'Button label'},{key:'url',label:'Button URL',type:'url'},{key:'recipients',label:'Recipients',type:'number'},{key:'opens',label:'Opens',type:'number'},{key:'clicks',label:'Clicks',type:'number'}]},
{id:'automation',label:'Automation',group:'Marketing',kind:'automation',singular:'workflow',description:'Connect a trigger to a useful next action.',statuses:['Draft','Active','Paused'],fields:[{key:'trigger',label:'Trigger',type:'select',options:['Lead created']},{key:'condition',label:'Condition',type:'select',options:['Every lead','Value above threshold']},{key:'threshold',label:'Minimum lead value (USD)',type:'number'},{key:'action',label:'Action',type:'select',options:['Create follow-up task']},{key:'taskTitle',label:'Follow-up task title',required:true},{key:'days',label:'Due in days',type:'number'}]},
{id:'leads',label:'Leads',group:'Marketing',kind:'lead',singular:'lead',description:'Keep the next conversation moving.',statuses:['New','Engaged','Qualified','Conversation','Opportunity','Customer'],fields:[{key:'email',label:'Email',type:'email'},{key:'company',label:'Company'},{key:'source',label:'Acquisition source',type:'select',options:['Organic search','Paid search','Social','Referral','Direct','Email','Other']},{key:'value',label:'Opportunity value (USD)',type:'number'},{key:'notes',label:'Conversation notes',type:'textarea'}]},
{id:'ecommerce',label:'eCommerce',group:'Marketing',kind:'product',singular:'product',description:'Bring product visibility and commercial performance together.',statuses:['Active','Draft','Archived'],fields:[{key:'sku',label:'SKU'},{key:'category',label:'Category'},{key:'url',label:'Product URL',type:'url'},{key:'views',label:'Product views',type:'number'},{key:'orders',label:'Orders',type:'number'},{key:'revenue',label:'Revenue (USD)',type:'number'},{key:'abandoned',label:'Abandoned checkouts',type:'number'}]},
{id:'website',label:'Website',group:'Marketing',kind:'page',singular:'page',description:'A healthier website starts with the details.',statuses:['Healthy','Needs attention','Not checked'],fields:[{key:'url',label:'Page URL',type:'url',required:true},{key:'purpose',label:'Page purpose'},{key:'technology',label:'Technology stack'},{key:'notes',label:'Technical and accessibility notes',type:'textarea'}]},
{id:'landing-pages',label:'Landing Pages',group:'Marketing',kind:'landing',singular:'landing page',description:'Connect the promise in your campaign to the next step.',statuses:['Draft','Live','Testing','Archived'],fields:[{key:'url',label:'Page URL',type:'url'},{key:'headline',label:'Headline'},{key:'cta',label:'Primary call to action'},{key:'sessions',label:'Sessions',type:'number'},{key:'conversions',label:'Conversions',type:'number'},{key:'notes',label:'Conversion hypothesis and observations',type:'textarea'}]},
{id:'digital-pr',label:'Digital PR',group:'Marketing',kind:'pr',singular:'opportunity',description:'Keep media opportunities and relationships in one place.',statuses:['Research','Outreach','Response','Published','Backlink / Mention'],fields:[{key:'publication',label:'Publication'},{key:'contact',label:'Contact / journalist'},{key:'email',label:'Contact email',type:'email'},{key:'url',label:'Publication / backlink URL',type:'url'},{key:'notes',label:'Pitch and relationship notes',type:'textarea'}]},
{id:'personas',label:'Buyer Personas',group:'Marketing',kind:'persona',singular:'persona',description:'Keep the people you want to reach at the center of the plan.',statuses:['Research','Validated'],fields:[{key:'jobTitle',label:'Job title'},{key:'industry',label:'Industry / company size'},{key:'goals',label:'Goals',type:'textarea'},{key:'challenges',label:'Challenges and pain points',type:'textarea'},{key:'triggers',label:'Buying triggers and objections',type:'textarea'},{key:'channels',label:'Preferred channels and search behavior',type:'textarea'},{key:'decision',label:'Decision-making process',type:'textarea'}]},
{id:'reports',label:'Reports',group:'Operations',kind:'report',singular:'report',description:'The progress, the lessons, and what comes next.'},
{id:'projects',label:'Projects',group:'Operations',kind:'task',singular:'task',description:'Turn the plan into work that moves forward.',statuses:['To do','In progress','In review','Done'],fields:[{key:'description',label:'Description',type:'textarea'},{key:'channel',label:'Workstream',type:'select',options:['SEO','Content','Advertising','Social','Website','Strategy','Email','General']}]},
{id:'settings',label:'Settings',group:'Operations',description:'Your workspace, people and connections.'}
];
export const byModule=Object.fromEntries(modules.map(x=>[x.id,x]));
export const rolePermissions:Record<string,string[]|null>={Owner:null,Admin:null,Manager:null,'SEO Specialist':['keyword','competitor','visibility','audit','page','task'],'Content Manager':['content','social','email','persona','task'],'Ads Manager':['campaign','landing','task'],Analyst:[],Client:[]};
export function canEdit(role:string,kind:string){const list=rolePermissions[role];return list===null||!!list?.includes(kind)}
