import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db,log,runtime} from './db';
import {demoClients,demoEntries,demoMetrics} from './demo';
import {canEdit,modules} from './modules';
import type {Client,Entry,Role,Workspace} from './types';
export class ApiError extends Error{constructor(message:string,public status=400){super(message)}}
export function responseError(error:unknown){console.error(error instanceof Error?error.message:error);return Response.json({error:error instanceof ApiError?error.message:'This action could not be completed. Your changes have not been discarded.'},{status:error instanceof ApiError?error.status:503})}
export async function body(req:Request,max=100000){if(req.headers.get('origin')!==new URL(req.url).origin)throw new ApiError('This request must come from your workspace.',403);const r=req.body?.getReader();if(!r)throw new ApiError('No data supplied.');let text='',n=0;const dec=new TextDecoder();while(true){const{done,value}=await r.read();if(done)break;n+=value.byteLength;if(n>max){await r.cancel();throw new ApiError('This request is too large.',413)}text+=dec.decode(value,{stream:true})}try{return JSON.parse(text+dec.decode())}catch{throw new ApiError('Invalid request data.')}}
export async function context(){const user=await getChatGPTUser();if(!user)throw new ApiError('Sign in with ChatGPT to save your workspace.',401);const database=db();let member=await database.prepare('SELECT * FROM members WHERE user_id = ? OR (email = ? AND user_id IS NULL) ORDER BY CASE WHEN user_id = ? THEN 0 ELSE 1 END LIMIT 1').bind(user.userId,user.email.toLowerCase(),user.userId).first<any>();if(!member){const orgId='org-'+user.userId;const date=new Date().toISOString();await database.batch([database.prepare('INSERT OR IGNORE INTO organizations (id,name,created_at) VALUES (?,?,?)').bind(orgId,'My marketing workspace',date),database.prepare('INSERT OR IGNORE INTO members (id,org_id,user_id,email,role,client_id) VALUES (?,?,?,?,?,NULL)').bind('member-'+user.userId,orgId,user.userId,user.email.toLowerCase(),'Owner')]);member=await database.prepare('SELECT * FROM members WHERE user_id = ?').bind(user.userId).first<any>()}else if(!member.user_id){await database.prepare('UPDATE members SET user_id = ? WHERE id = ?').bind(user.userId,member.id).run();member.user_id=user.userId}return {user,orgId:member.org_id as string,role:member.role as Role,assignedClient:member.client_id as string|null}}
export type Context=Awaited<ReturnType<typeof context>>;
export function allowed(c:Context,kind:string){if(!canEdit(c.role,kind))throw new ApiError('Your role has read-only access to this area.',403)}
export async function clientAccess(c:Context,id:string){const row=await db().prepare('SELECT * FROM clients WHERE id = ? AND org_id = ?').bind(id,c.orgId).first<any>();if(!row||(c.role==='Client'&&c.assignedClient!==id))throw new ApiError('This client is not available in your workspace.',404);return {...JSON.parse(row.data),id:row.id,orgId:row.org_id,name:row.name,createdAt:row.created_at} as Client}
export const mapEntry=(r:any):Entry=>({id:r.id,clientId:r.client_id,kind:r.kind,title:r.title,status:r.status,priority:r.priority,owner:r.owner,dueDate:r.due_date,projectId:r.project_id||'',relatedId:r.related_id||'',data:JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at});
export async function getEntries(id:string){const result=await db().prepare('SELECT * FROM entries WHERE client_id = ? ORDER BY created_at DESC').bind(id).all();return result.results.map(mapEntry)}
export async function seedDemo(c:Context){allowed(c,'project');const database=db();const orgClient=await database.prepare('SELECT id FROM clients WHERE org_id = ? LIMIT 1').bind(c.orgId).first();if(orgClient)throw new ApiError('A sample can only be added to an empty workspace.');const prefix=c.orgId+'-';const items=demoClients.map(x=>({...x,id:prefix+x.id,orgId:c.orgId}));const statements=items.map(x=>database.prepare('INSERT INTO clients (id,org_id,name,data,created_at) VALUES (?,?,?,?,?)').bind(x.id,c.orgId,x.name,JSON.stringify(x),x.createdAt));for(const x of demoEntries){const item={...x,id:prefix+x.id,clientId:prefix+x.clientId,projectId:x.projectId?prefix+x.projectId:'',relatedId:x.relatedId?prefix+x.relatedId:''};statements.push(insertEntry(item))}for(const cl of items){for(const m of demoMetrics(cl.name==='Fern & Form'?.65:1)){statements.push(database.prepare('INSERT INTO analytics (id,client_id,date,data,source) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),cl.id,m.date,JSON.stringify(m),'Demo dataset'))}}for(let i=0;i<statements.length;i+=80)await database.batch(statements.slice(i,i+80));await log(c.orgId,c.user.userId,'demo.created',items[0].id)}
export function insertEntry(e:Entry){return db().prepare('INSERT INTO entries (id,client_id,kind,title,status,priority,owner,due_date,project_id,related_id,data,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(e.id,e.clientId,e.kind,e.title,e.status,e.priority,e.owner,e.dueDate,e.projectId||null,e.relatedId||null,JSON.stringify(e.data),e.createdAt,e.updatedAt)}
export async function workspace(c:Context,clientId?:string):Promise<Workspace>{const results=await db().prepare('SELECT * FROM clients WHERE org_id = ? ORDER BY created_at').bind(c.orgId).all<any>();const clients:Client[]=results.results.filter(r=>c.role!=='Client'||r.id===c.assignedClient).map(r=>({...JSON.parse(r.data),id:r.id,orgId:r.org_id,name:r.name,createdAt:r.created_at}));const id=clientId||clients[0]?.id||'';if(id)await clientAccess(c,id);const entries=id?await getEntries(id):[];const m=id?await db().prepare('SELECT data FROM analytics WHERE client_id = ? ORDER BY date').bind(id).all<{data:string}>():{results:[]};const org=await db().prepare('SELECT * FROM organizations WHERE id = ?').bind(c.orgId).first<any>();const members=['Owner','Admin'].includes(c.role)?(await db().prepare('SELECT * FROM members WHERE org_id = ?').bind(c.orgId).all<any>()).results.map(x=>({id:x.id,email:x.email,role:x.role,clientId:x.client_id,userId:x.user_id})):[];return {user:{id:c.user.userId,name:c.user.fullName||c.user.email.split('@')[0],email:c.user.email},organization:{id:c.orgId,name:org.name},role:c.role,clients,clientId:id,entries,metrics:m.results.map(x=>JSON.parse(x.data)),members,aiEnabled:!!runtime('OPENAI_API_KEY'),demoMode:false}}
export function cleanText(v:unknown,max=1000){return typeof v==='string'?v.trim().slice(0,max):''}
export function safeUrl(value:unknown){if(!value)return '';const text=cleanText(value,2000);try{const u=new URL(text);if(!['https:','http:'].includes(u.protocol))throw Error();return u.href}catch{throw new ApiError('Enter a complete http or https URL.')}}
export async function limit(c:Context,action:string,max=30){const now=Date.now(),key=c.user.userId+':'+action+':'+Math.floor(now/3600000);const r=await db().prepare('INSERT INTO rate_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+3600000).first<{count:number}>();if(r&&r.count>max)throw new ApiError('This action has reached its hourly limit. Please try again later.',429)}
