import {modules} from './modules';
import {ApiError,cleanText,safeUrl,clientAccess,allowed,mapEntry,type Context} from './server';
import {db} from './db';
import type {Entry,DailyMetric} from './types';
export const kindDef=(kind:string)=>modules.find(x=>x.kind===kind);
export function validDate(x:unknown,required=false){const s=cleanText(x,10);if(!s&&!required)return '';if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||Number.isNaN(Date.parse(s))||new Date(s).toISOString().slice(0,10)!==s)throw new ApiError('Enter a valid date.');return s}
export function numeric(v:unknown,label:string){const n=Number(v||0);if(!Number.isFinite(n)||n<0||n>1e12)throw new ApiError(label+' must be a nonnegative number.');return n}
export async function validatedEntry(c:Context,raw:any,existing?:Entry){const kind=existing?.kind||cleanText(raw.kind,40),def=kindDef(kind);if((!def||['report'].includes(kind))&&kind!=='project')throw new ApiError('This type of record cannot be saved here.');allowed(c,kind);const clientId=existing?.clientId||cleanText(raw.clientId,160);await clientAccess(c,clientId);const title=cleanText(raw.title,240);if(!title)throw new ApiError('Give this record a name.');const statuses=def?.statuses||['Planned','In progress','Done'];const status=cleanText(raw.status)||statuses[0];if(!statuses.includes(status))throw new ApiError('Choose a valid status.');const data:Record<string,unknown>={};for(const f of def?.fields||[]){const value=raw.data?.[f.key];if(f.required&&(value===undefined||String(value).trim()===''))throw new ApiError(f.label+' is required.');if(f.type==='number')data[f.key]=numeric(value,f.label);else if(f.type==='url')data[f.key]=safeUrl(value);else if(f.type==='date')data[f.key]=validDate(value);else if(f.type==='select'){const s=cleanText(value)||f.options?.[0]||'';if(s&&!f.options?.includes(s))throw new ApiError('Choose a valid '+f.label.toLowerCase()+'.');data[f.key]=s}else {data[f.key]=cleanText(value,f.type==='textarea'?30000:2000);if(f.type==='email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(data[f.key])))throw new ApiError('Enter a valid email address.')}}
const priority=['Low','Medium','High'].includes(raw.priority)?raw.priority:'Medium';const projectId=cleanText(raw.projectId,160),relatedId=cleanText(raw.relatedId,160);for(const[id,project]of[[projectId,true],[relatedId,false]] as const){if(id){const ref=await db().prepare('SELECT id,kind FROM entries WHERE id = ? AND client_id = ?').bind(id,clientId).first<any>();if(!ref||(project&&ref.kind!=='project'))throw new ApiError('Linked records must belong to the selected client.')}}const date=new Date().toISOString();return {id:existing?.id||crypto.randomUUID(),clientId,kind,title,status,priority,owner:cleanText(raw.owner,120)||'Unassigned',dueDate:validDate(raw.dueDate),projectId,relatedId,data,createdAt:existing?.createdAt||date,updatedAt:date} as Entry}
export async function ownedEntry(c:Context,id:string){const r=await db().prepare('SELECT e.* FROM entries e INNER JOIN clients cl ON e.client_id = cl.id WHERE e.id = ? AND cl.org_id = ?').bind(id,c.orgId).first<any>();if(!r)throw new ApiError('This record is not available.',404);await clientAccess(c,r.client_id);return mapEntry(r)}
export const metricKeys=['sessions','organic','paid','social','referral','direct','leads','conversions','spend','revenue','impressions','clicks'] as const;
export function validateMetric(raw:any):DailyMetric{const m:any={date:validDate(raw.date,true)};for(const k of metricKeys)m[k]=numeric(raw[k],k);return m}
